//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace computerbucket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_tbl
    {
        public Category_tbl()
        {
            this.Parts_tbl = new HashSet<Parts_tbl>();
        }
    
        public int category_id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Parts_tbl> Parts_tbl { get; set; }
    }
}
