//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace computerbucket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custumer_tbl
    {
        public Custumer_tbl()
        {
            this.CustumerOrders = new HashSet<CustumerOrder>();
        }
    
        public int custumer_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
    
        public virtual ICollection<CustumerOrder> CustumerOrders { get; set; }
    }
}
