//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace computerbucket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboard_tbl
    {
        public Motherboard_tbl()
        {
            this.Comparison_tbl = new HashSet<Comparison_tbl>();
            this.OrderMotherboard_tbl = new HashSet<OrderMotherboard_tbl>();
        }
    
        public int motherboard_id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> qty_stock { get; set; }
    
        public virtual ICollection<Comparison_tbl> Comparison_tbl { get; set; }
        public virtual ICollection<OrderMotherboard_tbl> OrderMotherboard_tbl { get; set; }
    }
}
