//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace computerbucket
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ItemID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> BuildPCID { get; set; }
        public Nullable<int> PreBuildPCID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public short Quantity { get; set; }
        public float Discount { get; set; }
    
        public virtual BuildPC BuildPC { get; set; }
        public virtual Order Order { get; set; }
        public virtual PreBuildPC PreBuildPC { get; set; }
    }
}
