//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace computerbucket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts_tbl
    {
        public Parts_tbl()
        {
            this.Comparison_tbl = new HashSet<Comparison_tbl>();
        }
    
        public int part_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> qty_stock { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Category_tbl Category_tbl { get; set; }
        public virtual ICollection<Comparison_tbl> Comparison_tbl { get; set; }
    }
}
