//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace computerbucket
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreBuildPC
    {
        public PreBuildPC()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int PreBuildPCID { get; set; }
        public int PCTypeID { get; set; }
        public string Motherboad { get; set; }
        public string Processor { get; set; }
        public string GraphicCard { get; set; }
        public string RAM { get; set; }
        public string Hard_Drive { get; set; }
        public string SSD { get; set; }
        public string PowerSupply { get; set; }
        public string CPUCooling { get; set; }
        public string ThermalPaste { get; set; }
        public string InternalDrive { get; set; }
        public string OperatingSystem { get; set; }
        public string ComputerCase { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual PCType PCType { get; set; }
    }
}
